# Generated by Django 6.0.5 on 2026-06-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='inactivity_days',
            field=models.IntegerField(default=7, help_text='Days of inactivity before sending'),
        ),
        migrations.AddField(
            model_name='letter',
            name='inactivity_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='send_on_inactivity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('not_scheduled', 'Not Scheduled'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('inactivity_triggered', 'Waiting for Inactivity Trigger')], default='not_scheduled', max_length=20),
        ),
    ]
