# Generated by Django 6.0.5 on 2026-06-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0002_letter_inactivity_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='inactivity_days',
            field=models.IntegerField(blank=True, default=7, help_text='Days of inactivity before sending', null=True),
        ),
    ]
