# Generated by Django 6.0.5 on 2026-06-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0003_alter_letter_inactivity_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment (PDF, DOC, images, etc.)', null=True, upload_to='message_attachments/%Y/%m/%d/'),
        ),
    ]
