# Generated by Django 6.0.5 on 2026-06-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0004_letter_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='last_checked',
        ),
    ]
