# Generated by Django 6.0.5 on 2026-06-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
