# Generated by Django 6.0.5 on 2026-06-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_c_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_user',
            name='is_staff',
        ),
    ]
