# Generated by Django 6.0.5 on 2026-06-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_c_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
