# Generated by Django 6.0.5 on 2026-06-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_c_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
