# Generated by Django 6.0.5 on 2026-06-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usertoken_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='last_activity',
        ),
        migrations.AddField(
            model_name='c_user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
