# Generated by Django 6.0.5 on 2026-06-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_usertoken_last_activity_c_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_user',
            name='first_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c_user',
            name='last_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
